# Generated by Django 6.0 on 2026-01-14 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='name',
            field=models.CharField(default='/static/dreams_app/images/placeholder.png', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dream',
            name='analysis_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dream',
            name='image',
            field=models.URLField(blank=True, default='/static/dreams_app/images/placeholder.png', null=True),
        ),
        migrations.AlterField(
            model_name='dream',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
