# Generated by Django 6.0 on 2026-01-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams_app', '0002_dream_name_alter_dream_analysis_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dream_images/'),
        ),
    ]
